### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :usb-serial-for-android.

### ISSUE THREAD

**Issue by ewangsoft** [AndProx/AndProx#25]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :usb-serial-for-android.

android studio 3.2.1
jre:1.8.0

**Comment by micolous** [comment]
Please read the build instructions. You have not checked out the submodules.

https://github.com/AndProx/AndProx/blob/master/HACKING.md#getting-the-code
