### ISSUE TITLE
Allow Copying of Output

### ISSUE THREAD

**Issue by h4waii** [AndProx/AndProx#26]
Can the property of the output window be changed to allow copying text? Would make it much easier to grab data and paste it into the command window.

**Comment by micolous** [comment]
Fixed in #29.

**Comment by h4waii** [comment]
Just did a pull and built a new APK, but I don't seem to be able to select text in the text box still.

**Comment by Cheeks300zx** [comment]
Same here I can't select text.

**Comment by h4waii** [comment]
Works on latest release. Thanks!
