### ISSUE TITLE
Why not supported Sony Xperia ?

### ISSUE THREAD

**Issue by maxben14** [AndProx/AndProx#30]
I try install app on Sony Xperia m2 but not installed. Why ?

**Comment by micolous** [comment]
Your version of Android is out of date (#7).

You should be able to get a new version from Sony: https://support.sonymobile.com/global-en/xperiam2/kb/80193074618bd4a7014db732b8d3007ed7/

**Comment by maxben14** [comment]
I want build app on android 4.2.1. Can you write is it possible to rewrite your application under 4.2.1?
Can you say me how build app on 4.2.1 please.

**Comment by micolous** [comment]
I only support Android 5.0 and later (see #7). Sony claim Android 5.1 is available for your device. Please contact Sony if you need help moving to this version of Android.
