### ISSUE TITLE
Can you help me port flashrom to an Android app?

### ISSUE THREAD

**Issue by Droid-MAX** [AndProx/AndProx#37]
[flashrom](https://www.flashrom.org/Flashrom)

[stm32-vserprog](https://github.com/dword1511/stm32-vserprog)

and my blog at [here](https://droid-max.github.io/2019/01/12/Use_the_phone_to_program_spi_flash_chip/)

If you have any ideas, please reply me in time, thank you.

**Comment by micolous** [comment]
Sorry, no, I already have too many side projects (AndProx is one of them!).

In the case of Flashrom, it would be particularly difficult as one would need to rewrite all of the programmer drivers that handle USB, or build a shim for libusb to bring it back into JNI. This would be in addition to refactoring enough of Flashrom into a library.  At that point you've rewritten a big chunk of Flashrom.

This would also _only_ work for USB programmers -- unless you want to use a rooted device.

By comparison, AndProx "merely" uses an existing Android USB serial device driver library. Proxmark3 already included OS-specific serial functionality, and had enough hooks to allow me to trick it into working.

If doing it for "just you", then just root your Android device and then using the NDK to cross-compile the existing Flashrom toolset as statically linked binaries.

I'm planning to write a talk about "how to port Linux command-line programs to Android," which would cover what I've learned with AndProx and interfacing with hardware on Android.
