### ISSUE TITLE
USB cable to the Proxmark3 was unplugged error

### ISSUE THREAD

**Issue by n00ldev** [AndProx/AndProx#40]
Proxmark is disconnected anytime a non instant command executed. Weather it is a snoop or continuous read, after about 10 seconds an error "The USB cable to the Proxmark3 was unplugged" appears even with unlocked screen.

## Expected behaviour
These commands should work until the button is pressed. It works flawlessly on PC.

## Actual behaviour
USB connection to the PM3 is lost after some time.

## Proxmark details (required!)
proxmark3> hw version
Prox/RFID mark3 RFID instrument
bootrom: master/v3.1.0-87-g905d297-suspect 2019-04-19 19:05:08
os: master/v3.1.0-87-g905d297-suspect 2019-04-19 19:05:11
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2019/03/20 at 08:08:07
SmartCard Slot: not available

uC: AT91SAM7S512 Rev B
Embedded Processor: ARM7TDMI
Nonvolatile Program Memory Size: 512K bytes. Used: 206188 bytes (39). Free: 318100 bytes (61).
Second Nonvolatile Program Memory Size: None
Internal SRAM Size: 64K bytes
Architecture Identifier: AT91SAM7Sxx Series
Nonvolatile Program Memory Type: Embedded Flash Memory

proxmark3> hw status
#db# Memory
#db# BIGBUF_SIZE.............40000
#db# Available memory........40000
#db# Tracing
#db# tracing ................1
#db# traceLen ...............0
#db# Currently loaded FPGA image:
#db# fpga_hf.bit built for 2s30vq100 on 2019/03/20 at 08:08:07
#db# Smart card module (ISO 7816)
#db# version.................FAILED
#db# LF Sampling config:
#db# [q] divisor: 95
#db# [b] bps: 8
#db# [d] decimation: 1
#db# [a] averaging: 1
#db# [t] trigger threshold: 0
#db# USB Speed:
#db# Sending USB packets to client...
#db# Time elapsed: 1500ms
#db# Bytes transferred: 941568
#db# USB Transfer Speed PM3 -> Client = 627712 Bytes/s
#db# Various
#db# MF_DBGLEVEL........2
#db# ToSendMax..........-907430187
#db# ToSendBit..........0

## Device details (required!)

AndProx version: 2.0.4 (95)
PM3 Client version: v3.1.0/HEAD
Build timestamp: 2018-11-25T05:05:27Z
Model: EML-L29 (HWEML)
Product: EML-L29
Manufacturer: HUAWEI (HUAWEI)
RAM: 3.6 GiB (1.0 GiB free)
Android OS: 9 (API 28)
Android Build: HUAWEIEML-L29

USB Host: yes
Found 1 USB device(s):
- /dev/bus/usb/002/002 (9ac4:4b8f)
Name: proxmark3
Could not retrieve serial number!

Found 1 suitable driver(s):
- /dev/bus/usb/002/002 (9ac4:4b8f)
Port 0: CdcAcmSerialPort
Detected PM3!

**Comment by micolous** [comment]
This is the same as #35.
