### ISSUE TITLE
Can't connect via USB - reverse charge only

### ISSUE THREAD

**Issue by jimmid709** [AndProx/AndProx#51]
When I plug the Proxmark3 in, it prompts to open andprox, but won't connect.  When I check USB settings it says reverse charging.
I change to transfer files, but after 1 second it changes back to reverse charging. I won't stay on file transfer. 
I read somewhere that it is a safety feature in new versions of Android.  I can't connect my Proxmark3 to Android for any app!

**Comment by slycooper724** [comment]
My instinct says the developers have abandoned this project. I haven't seen any activity since 2019. Its two years later, and no reply on issues and etc. This truly stinks since this looks like it has a lot of potential still, but it hasn't seen any progress since.

**Comment by micolous** [comment]
"Reverse charging" is correct - your device needs to be in USB host mode.  When you have it in File Transfer / Android Auto mode, it is in USB device/peripheral mode.

The fact that it's prompting to use AndProx means that it is at least _trying_ to communicate with your Proxmark.

You haven't given enough information here for me to be able to advise further: I don't know what precise error message you get, you haven't included the "System Info" from the app, you haven't said what PM3 device you have, or even if you have [the correct firmware](https://github.com/AndProx/AndProx/blob/master/docs/compatibility.md#firmware-compatibility).
